/**
 * Gear catalog — avatar looks unlocked through XP progression.
 *
 * Each item maps to an AvatarColors preset that, when "equipped", is written
 * into settingsStore's avatar field so CesiumViewer picks it up immediately.
 *
 * Wave 37.C: expanded to 120+ items across 6 categories matching Zwift breadth.
 * Levels span 1–50 giving meaningful rewards throughout the progression curve.
 */

import type { AvatarColors } from '@/lib/avatarConfig';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type GearKind = 'bike' | 'helmet' | 'kit' | 'glasses' | 'shoes' | 'bottle';

export interface GearItem {
  id: string;
  name: string;
  kind: GearKind;
  /** Sub-category for filtering — 'aero', 'climber', 'gravel', 'tt', 'mtb', etc. */
  subCategory?: string;
  unlockLevel: number;
  /** Primary colorway — drives the avatar render. */
  colors: AvatarColors;
  /** Optional accent palette for kit patterns (secondary / tertiary stripes). */
  accentColors?: { primary: string; secondary: string; tertiary?: string };
  /** Shape hint the avatar renderer uses to pick geometry. */
  shape?: string;
  description?: string;
}

// ---------------------------------------------------------------------------
// Legacy HelmetItem — kept for backward compat with Garage.tsx import
// ---------------------------------------------------------------------------

export interface HelmetItem {
  id: string;
  name: string;
  /** Dominant shell color shown in the helmet SVG illustration. */
  defaultColor: string;
  /** Secondary / vent color. */
  accentColor: string;
  /** Minimum level required to equip (mirrors GearItem.unlockLevel semantics). */
  unlockLevel: number;
}

// ---------------------------------------------------------------------------
// GEAR_CATALOG — 120+ items across all 6 categories
// ---------------------------------------------------------------------------

export const GEAR_CATALOG: GearItem[] = [

  // ==========================================================================
  // BIKES — 50+ items
  // ==========================================================================

  // ── Starter tier (1–5) ────────────────────────────────────────────────────
  {
    id: 'bike-starter',
    name: 'Basic Road Bike',
    kind: 'bike',
    subCategory: 'all-rounder',
    unlockLevel: 1,
    shape: 'allRounder',
    description: 'A reliable aluminium all-rounder to get you rolling.',
    colors: { frame: '#6b7280', wheel: '#374151', kit: '#22d3ee', skin: '#d8a877', helmet: '#0ea5e9', accent: '#f59e0b' },
  },
  {
    id: 'midnight-road',
    name: 'Midnight Road',
    kind: 'bike',
    subCategory: 'all-rounder',
    unlockLevel: 2,
    shape: 'allRounder',
    description: 'Matte black finish with electric blue detailing.',
    colors: { frame: '#0f172a', wheel: '#1e293b', kit: '#22d3ee', skin: '#d8a877', helmet: '#0284c7', accent: '#38bdf8' },
  },
  {
    id: 'trail-gravel',
    name: 'Trail Gravel',
    kind: 'bike',
    subCategory: 'gravel',
    unlockLevel: 4,
    shape: 'gravel',
    description: 'Rugged gravel geometry, olive drab with chartreuse accents.',
    colors: { frame: '#3f6212', wheel: '#1a2e05', kit: '#84cc16', skin: '#d8a877', helmet: '#65a30d', accent: '#fde047' },
  },
  {
    id: 'stealth-carbon',
    name: 'Stealth Carbon',
    kind: 'bike',
    subCategory: 'aero',
    unlockLevel: 5,
    shape: 'aero',
    description: 'Full-carbon aero frame in raw weave — barely visible at speed.',
    colors: { frame: '#1c1c1e', wheel: '#000000', kit: '#1e293b', skin: '#d8a877', helmet: '#334155', accent: '#e2e8f0' },
  },
  {
    id: 'fixie-urban',
    name: 'Urban Fixie',
    kind: 'bike',
    subCategory: 'fixie',
    unlockLevel: 3,
    shape: 'fixie',
    description: 'Track-geometry fixie for the city courier aesthetic.',
    colors: { frame: '#dc2626', wheel: '#111827', kit: '#ef4444', skin: '#d8a877', helmet: '#b91c1c', accent: '#fef2f2' },
  },

  // ── Standard tier (6–15) ──────────────────────────────────────────────────
  {
    id: 'gravel-slate',
    name: 'Gravel Slate',
    kind: 'bike',
    subCategory: 'gravel',
    unlockLevel: 6,
    shape: 'gravel',
    description: 'Slate grey gravel rig — ready for the unknown lane.',
    colors: { frame: '#475569', wheel: '#1e293b', kit: '#94a3b8', skin: '#d8a877', helmet: '#64748b', accent: '#f1f5f9' },
  },
  {
    id: 'mtb-hardtail',
    name: 'Hardtail MTB',
    kind: 'bike',
    subCategory: 'mtb-hardtail',
    unlockLevel: 6,
    shape: 'mtbHardtail',
    description: 'Aluminium hardtail with 120mm fork — trail-ready.',
    colors: { frame: '#1d4ed8', wheel: '#1e3a8a', kit: '#60a5fa', skin: '#d8a877', helmet: '#2563eb', accent: '#bfdbfe' },
  },
  {
    id: 'arctic-white',
    name: 'Arctic White',
    kind: 'bike',
    subCategory: 'all-rounder',
    unlockLevel: 7,
    shape: 'allRounder',
    description: 'Gleaming white with ice-blue highlights.',
    colors: { frame: '#f8fafc', wheel: '#94a3b8', kit: '#e2e8f0', skin: '#d8a877', helmet: '#cbd5e1', accent: '#22d3ee' },
  },
  {
    id: 'vintage-steel',
    name: 'Vintage Steel',
    kind: 'bike',
    subCategory: 'vintage',
    unlockLevel: 8,
    shape: 'vintage',
    description: 'Classic lugged steel — the ride quality that never goes out of style.',
    colors: { frame: '#78350f', wheel: '#3b1f0c', kit: '#d97706', skin: '#d8a877', helmet: '#b45309', accent: '#fef3c7' },
  },
  {
    id: 'summit-climber',
    name: 'Summit Climber',
    kind: 'bike',
    subCategory: 'climber',
    unlockLevel: 8,
    shape: 'climber',
    description: 'Ultra-light climber geometry, built for mountain passes.',
    colors: { frame: '#dc2626', wheel: '#7f1d1d', kit: '#fca5a5', skin: '#d8a877', helmet: '#ef4444', accent: '#fef2f2' },
  },
  {
    id: 'tt-viper',
    name: 'TT Viper',
    kind: 'bike',
    subCategory: 'time-trial',
    unlockLevel: 9,
    shape: 'tt',
    description: 'Full TT geometry with disc wheel and aggressive cockpit.',
    colors: { frame: '#1e293b', wheel: '#0f172a', kit: '#0ea5e9', skin: '#d8a877', helmet: '#0284c7', accent: '#7dd3fc' },
  },
  {
    id: 'cobalt-aero',
    name: 'Cobalt Aero',
    kind: 'bike',
    subCategory: 'aero',
    unlockLevel: 10,
    shape: 'aero',
    description: 'Wind-tunnel tested aero frame in deep cobalt blue.',
    colors: { frame: '#1e3a5f', wheel: '#0f2746', kit: '#3b82f6', skin: '#d8a877', helmet: '#1d4ed8', accent: '#93c5fd' },
  },
  {
    id: 'mtb-hardtail-orange',
    name: 'Hardtail Blaze',
    kind: 'bike',
    subCategory: 'mtb-hardtail',
    unlockLevel: 10,
    shape: 'mtbHardtail',
    description: 'Blazing orange hardtail that pops on every trail.',
    colors: { frame: '#ea580c', wheel: '#431407', kit: '#fb923c', skin: '#d8a877', helmet: '#c2410c', accent: '#fed7aa' },
  },
  {
    id: 'gravel-king',
    name: 'Gravel King',
    kind: 'bike',
    subCategory: 'gravel',
    unlockLevel: 11,
    shape: 'gravel',
    description: 'Long-haul gravel adventurer in desert tan.',
    colors: { frame: '#92400e', wheel: '#451a03', kit: '#fbbf24', skin: '#d8a877', helmet: '#d97706', accent: '#fef3c7' },
  },
  {
    id: 'emerald-climber',
    name: 'Emerald Climber',
    kind: 'bike',
    subCategory: 'climber',
    unlockLevel: 12,
    shape: 'climber',
    description: 'Featherweight emerald frame — shed watts on every gradient.',
    colors: { frame: '#065f46', wheel: '#022c22', kit: '#34d399', skin: '#d8a877', helmet: '#059669', accent: '#a7f3d0' },
  },
  {
    id: 'fixie-chrome',
    name: 'Chrome Fixie',
    kind: 'bike',
    subCategory: 'fixie',
    unlockLevel: 13,
    shape: 'fixie',
    description: 'Polished chrome single-speed — pure urban cool.',
    colors: { frame: '#e2e8f0', wheel: '#94a3b8', kit: '#f8fafc', skin: '#d8a877', helmet: '#cbd5e1', accent: '#0ea5e9' },
  },
  {
    id: 'mtb-fullsus',
    name: 'Full-Sus MTB',
    kind: 'bike',
    subCategory: 'mtb-fullsus',
    unlockLevel: 14,
    shape: 'mtbFullSus',
    description: '150mm travel full-suspension — eats rough terrain for breakfast.',
    colors: { frame: '#15803d', wheel: '#052e16', kit: '#4ade80', skin: '#d8a877', helmet: '#16a34a', accent: '#bbf7d0' },
  },
  {
    id: 'rose-gold',
    name: 'Rose Gold',
    kind: 'bike',
    subCategory: 'all-rounder',
    unlockLevel: 14,
    shape: 'allRounder',
    description: 'Brushed rose gold aluminium — turns heads on every climb.',
    colors: { frame: '#be9f8a', wheel: '#6b4c38', kit: '#fda4af', skin: '#d8a877', helmet: '#e879a8', accent: '#fcd34d' },
  },
  {
    id: 'tt-storm',
    name: 'TT Storm',
    kind: 'bike',
    subCategory: 'time-trial',
    unlockLevel: 15,
    shape: 'tt',
    description: 'Dark matte TT sled — optimised for every second on the clock.',
    colors: { frame: '#18181b', wheel: '#09090b', kit: '#6d28d9', skin: '#d8a877', helmet: '#7c3aed', accent: '#c4b5fd' },
  },

  // ── Premium tier (16–30) ──────────────────────────────────────────────────
  {
    id: 'ebike-urban',
    name: 'Urban E-Bike',
    kind: 'bike',
    subCategory: 'e-bike',
    unlockLevel: 16,
    shape: 'ebike',
    description: 'Integrated battery, smooth commuter geometry.',
    colors: { frame: '#374151', wheel: '#1f2937', kit: '#6ee7b7', skin: '#d8a877', helmet: '#34d399', accent: '#a7f3d0' },
  },
  {
    id: 'sky-climber',
    name: 'Sky Climber',
    kind: 'bike',
    subCategory: 'climber',
    unlockLevel: 19,
    shape: 'climber',
    description: 'Sub-700g frame weight — feels like flying up a col.',
    colors: { frame: '#0ea5e9', wheel: '#0369a1', kit: '#7dd3fc', skin: '#d8a877', helmet: '#0284c7', accent: '#f0f9ff' },
  },
  {
    id: 'mtb-fullsus-dark',
    name: 'Dark Matter MTB',
    kind: 'bike',
    subCategory: 'mtb-fullsus',
    unlockLevel: 20,
    shape: 'mtbFullSus',
    description: 'Blacked-out full-sus with red pivot accents.',
    colors: { frame: '#0f0f0f', wheel: '#050505', kit: '#1f1f1f', skin: '#d8a877', helmet: '#171717', accent: '#ef4444' },
  },
  {
    id: 'aero-blade',
    name: 'Aero Blade Pro',
    kind: 'bike',
    subCategory: 'aero',
    unlockLevel: 20,
    shape: 'aero',
    description: 'Refined aero blade — wind-cheating at every watt.',
    colors: { frame: '#1e293b', wheel: '#0f172a', kit: '#f59e0b', skin: '#d8a877', helmet: '#d97706', accent: '#fef3c7' },
  },
  {
    id: 'carbon-road-yellow',
    name: 'Yellow Leader',
    kind: 'bike',
    subCategory: 'all-rounder',
    unlockLevel: 22,
    shape: 'allRounder',
    description: 'Yellow & black — inspired by the maillot jaune.',
    colors: { frame: '#eab308', wheel: '#1c1c1e', kit: '#facc15', skin: '#d8a877', helmet: '#ca8a04', accent: '#fefce8' },
    accentColors: { primary: '#eab308', secondary: '#1c1c1e' },
  },
  {
    id: 'vintage-campy',
    name: 'Campionissimo Steel',
    kind: 'bike',
    subCategory: 'vintage',
    unlockLevel: 22,
    shape: 'vintage',
    description: 'Italian racing steel in Bianchi celeste green — timeless.',
    colors: { frame: '#2dd4bf', wheel: '#134e4a', kit: '#99f6e4', skin: '#d8a877', helmet: '#0d9488', accent: '#f0fdf4' },
  },
  {
    id: 'carbon-road-red',
    name: 'Ineos Red',
    kind: 'bike',
    subCategory: 'all-rounder',
    unlockLevel: 24,
    shape: 'allRounder',
    description: 'Red, white & black — inspired by Team Sky / Ineos colour scheme.',
    colors: { frame: '#dc2626', wheel: '#1c1c1e', kit: '#ef4444', skin: '#d8a877', helmet: '#991b1b', accent: '#f8fafc' },
    accentColors: { primary: '#dc2626', secondary: '#f8fafc', tertiary: '#1c1c1e' },
  },
  {
    id: 'tt-midnight',
    name: 'TT Midnight Pro',
    kind: 'bike',
    subCategory: 'time-trial',
    unlockLevel: 25,
    shape: 'tt',
    description: 'UCI-legal TT machine in midnight with holographic decals.',
    colors: { frame: '#0a0a1a', wheel: '#04040d', kit: '#7c3aed', skin: '#d8a877', helmet: '#5b21b6', accent: '#818cf8' },
  },
  {
    id: 'all-road-pro',
    name: 'All-Road Pro',
    kind: 'bike',
    subCategory: 'all-rounder',
    unlockLevel: 27,
    shape: 'allRounder',
    description: 'Endurance geometry in deep forest green — from café to col.',
    colors: { frame: '#14532d', wheel: '#052e16', kit: '#22c55e', skin: '#d8a877', helmet: '#15803d', accent: '#dcfce7' },
  },
  {
    id: 'carbon-aero-deep-rim',
    name: 'Deep Rim Aero',
    kind: 'bike',
    subCategory: 'aero',
    unlockLevel: 28,
    shape: 'aero',
    description: '80mm carbon deep-section wheels — feels like a TT on a road frame.',
    colors: { frame: '#18181b', wheel: '#27272a', kit: '#a1a1aa', skin: '#d8a877', helmet: '#3f3f46', accent: '#e4e4e7' },
  },
  {
    id: 'ebike-cargo',
    name: 'Cargo E-Bike',
    kind: 'bike',
    subCategory: 'e-bike',
    unlockLevel: 30,
    shape: 'ebike',
    description: 'Heavy-duty cargo e-bike — built to haul.',
    colors: { frame: '#292524', wheel: '#1c1917', kit: '#44403c', skin: '#d8a877', helmet: '#57534e', accent: '#78716c' },
  },
  {
    id: 'gravel-expedition',
    name: 'Expedition Gravel',
    kind: 'bike',
    subCategory: 'gravel',
    unlockLevel: 28,
    shape: 'gravel',
    description: 'Bikepacking-ready gravel tourer with mounts for everything.',
    colors: { frame: '#713f12', wheel: '#451a03', kit: '#a16207', skin: '#d8a877', helmet: '#92400e', accent: '#fef9c3' },
  },
  {
    id: 'chrome-whip',
    name: 'Chrome Whip',
    kind: 'bike',
    subCategory: 'all-rounder',
    unlockLevel: 18,
    shape: 'allRounder',
    description: 'Mirror-polished chrome finish — dazzling in sunlight.',
    colors: { frame: '#d1d5db', wheel: '#9ca3af', kit: '#f3f4f6', skin: '#d8a877', helmet: '#e5e7eb', accent: '#22d3ee' },
  },
  {
    id: 'ebike-mountain',
    name: 'E-Mountain',
    kind: 'bike',
    subCategory: 'e-bike',
    unlockLevel: 22,
    shape: 'ebike',
    description: 'High-torque e-MTB — conquers climbs without breaking a sweat.',
    colors: { frame: '#1e3a8a', wheel: '#172554', kit: '#3b82f6', skin: '#d8a877', helmet: '#1d4ed8', accent: '#dbeafe' },
  },

  // ── Elite tier (31–50) ────────────────────────────────────────────────────
  {
    id: 'vintage-randonneur',
    name: 'Randonneur Classic',
    kind: 'bike',
    subCategory: 'vintage',
    unlockLevel: 33,
    shape: 'vintage',
    description: 'A French randonneur in cream & burgundy — elegance over speed.',
    colors: { frame: '#9d174d', wheel: '#4c0519', kit: '#fda4af', skin: '#d8a877', helmet: '#be185d', accent: '#fdf2f8' },
  },
  {
    id: 'mtb-hardtail-elite',
    name: 'XC Elite Hardtail',
    kind: 'bike',
    subCategory: 'mtb-hardtail',
    unlockLevel: 34,
    shape: 'mtbHardtail',
    description: 'Carbon XC hardtail — cross-country race geometry.',
    colors: { frame: '#4f46e5', wheel: '#312e81', kit: '#818cf8', skin: '#d8a877', helmet: '#4338ca', accent: '#e0e7ff' },
  },
  {
    id: 'tt-world-hour',
    name: 'Hour Record Special',
    kind: 'bike',
    subCategory: 'time-trial',
    unlockLevel: 35,
    shape: 'tt',
    description: 'Replica of the bike used in UCI Hour Record attempts.',
    colors: { frame: '#7c3aed', wheel: '#4c1d95', kit: '#8b5cf6', skin: '#d8a877', helmet: '#6d28d9', accent: '#ede9fe' },
  },
  {
    id: 'tt-triathlon',
    name: 'Triathlon Rocket',
    kind: 'bike',
    subCategory: 'time-trial',
    unlockLevel: 36,
    shape: 'tt',
    description: 'Integrated aero cockpit optimised for triathlon T2 exits.',
    colors: { frame: '#0f766e', wheel: '#042f2e', kit: '#2dd4bf', skin: '#d8a877', helmet: '#0d9488', accent: '#ccfbf1' },
  },
  {
    id: 'fixie-velodrome',
    name: 'Velodrome Track',
    kind: 'bike',
    subCategory: 'fixie',
    unlockLevel: 38,
    shape: 'fixie',
    description: 'UCI track-legal geometry — razor sharp on the boards.',
    colors: { frame: '#fbbf24', wheel: '#1c1c1e', kit: '#fde68a', skin: '#d8a877', helmet: '#d97706', accent: '#fffbeb' },
  },
  {
    id: 'gravel-titanium',
    name: 'Titanium Gravel',
    kind: 'bike',
    subCategory: 'gravel',
    unlockLevel: 40,
    shape: 'gravel',
    description: 'Brushed titanium — the once-in-a-lifetime gravel bike.',
    colors: { frame: '#9ca3af', wheel: '#4b5563', kit: '#d1d5db', skin: '#d8a877', helmet: '#6b7280', accent: '#f9fafb' },
  },
  {
    id: 'mtb-enduro-pro',
    name: 'Enduro Pro',
    kind: 'bike',
    subCategory: 'mtb-fullsus',
    unlockLevel: 32,
    shape: 'mtbFullSus',
    description: '170mm travel carbon enduro rig — no hill is too gnarly.',
    colors: { frame: '#dc2626', wheel: '#1c1c1e', kit: '#f87171', skin: '#d8a877', helmet: '#991b1b', accent: '#fef2f2' },
  },
  {
    id: 'gravel-desert',
    name: 'Desert Gravel',
    kind: 'bike',
    subCategory: 'gravel',
    unlockLevel: 42,
    shape: 'gravel',
    description: 'Sandy tan frame built for epic gravel epics in the dust.',
    colors: { frame: '#d97706', wheel: '#78350f', kit: '#fcd34d', skin: '#d8a877', helmet: '#b45309', accent: '#fffbeb' },
  },
  {
    id: 'legend-climber',
    name: 'Mountain Legend',
    kind: 'bike',
    subCategory: 'climber',
    unlockLevel: 45,
    shape: 'climber',
    description: 'Elite climber frame in world champion rainbow.',
    colors: { frame: '#f8fafc', wheel: '#1c1c1e', kit: '#e2e8f0', skin: '#d8a877', helmet: '#94a3b8', accent: '#dc2626' },
    accentColors: { primary: '#dc2626', secondary: '#f59e0b', tertiary: '#22c55e' },
  },
  {
    id: 'aero-gold',
    name: 'Gold Standard Aero',
    kind: 'bike',
    subCategory: 'aero',
    unlockLevel: 50,
    shape: 'aero',
    description: 'The pinnacle — full-gold aero masterpiece for the elite.',
    colors: { frame: '#78350f', wheel: '#451a03', kit: '#f59e0b', skin: '#d8a877', helmet: '#d97706', accent: '#fef3c7' },
    accentColors: { primary: '#f59e0b', secondary: '#fef3c7' },
  },
  {
    id: 'carbon-tt-disc',
    name: 'Carbon TT Disc',
    kind: 'bike',
    subCategory: 'time-trial',
    unlockLevel: 44,
    shape: 'tt',
    description: 'Full disc wheel rear, 60mm carbon front — for the flat specialists.',
    colors: { frame: '#18181b', wheel: '#09090b', kit: '#3f3f46', skin: '#d8a877', helmet: '#27272a', accent: '#f59e0b' },
  },
  {
    id: 'aero-ocean',
    name: 'Ocean Aero',
    kind: 'bike',
    subCategory: 'aero',
    unlockLevel: 38,
    shape: 'aero',
    description: 'Deep ocean teal aero frame — calm on the outside, fast on the inside.',
    colors: { frame: '#0f766e', wheel: '#042f2e', kit: '#14b8a6', skin: '#d8a877', helmet: '#0d9488', accent: '#99f6e4' },
  },
  {
    id: 'climber-white-red',
    name: 'Alpine Purity',
    kind: 'bike',
    subCategory: 'climber',
    unlockLevel: 30,
    shape: 'climber',
    description: 'White frame with red accents — classic Alpine climber look.',
    colors: { frame: '#f8fafc', wheel: '#e2e8f0', kit: '#fca5a5', skin: '#d8a877', helmet: '#f8fafc', accent: '#dc2626' },
  },
  {
    id: 'gravel-adventure-pink',
    name: 'Adventure Pink',
    kind: 'bike',
    subCategory: 'gravel',
    unlockLevel: 17,
    shape: 'gravel',
    description: 'Vivid pink gravel bike — stand out on every fire road.',
    colors: { frame: '#ec4899', wheel: '#831843', kit: '#f9a8d4', skin: '#d8a877', helmet: '#db2777', accent: '#fdf2f8' },
  },
  {
    id: 'mtb-hardtail-purple',
    name: 'Purple Reign Hardtail',
    kind: 'bike',
    subCategory: 'mtb-hardtail',
    unlockLevel: 26,
    shape: 'mtbHardtail',
    description: 'Bold purple hardtail with gold decals.',
    colors: { frame: '#7e22ce', wheel: '#3b0764', kit: '#a855f7', skin: '#d8a877', helmet: '#6d28d9', accent: '#fbbf24' },
  },
  {
    id: 'climber-ultralight-white',
    name: 'Ultralight Climber',
    kind: 'bike',
    subCategory: 'climber',
    unlockLevel: 36,
    shape: 'climber',
    description: 'Carbon monocoque climber — every gram stripped for the mountains.',
    colors: { frame: '#f8fafc', wheel: '#cbd5e1', kit: '#e2e8f0', skin: '#d8a877', helmet: '#94a3b8', accent: '#6366f1' },
  },
  {
    id: 'tt-chrono-black',
    name: 'Chrono TT',
    kind: 'bike',
    subCategory: 'time-trial',
    unlockLevel: 48,
    shape: 'tt',
    description: 'The ultimate TT weapon — maximum integration, minimum drag.',
    colors: { frame: '#09090b', wheel: '#050507', kit: '#18181b', skin: '#d8a877', helmet: '#1c1c1e', accent: '#f59e0b' },
  },

  // ==========================================================================
  // HELMETS — 30+ items
  // ==========================================================================

  // ── Starter tier ─────────────────────────────────────────────────────────
  {
    id: 'helmet-starter',
    name: 'Starter Lid',
    kind: 'helmet',
    subCategory: 'road-ventilated',
    unlockLevel: 1,
    shape: 'ventilated',
    description: 'Basic vented road helmet — safe and breathable.',
    colors: { frame: '#94a3b8', wheel: '#64748b', kit: '#e2e8f0', skin: '#d8a877', helmet: '#94a3b8', accent: '#e2e8f0' },
  },
  {
    id: 'helmet-aero',
    name: 'Aero TT',
    kind: 'helmet',
    subCategory: 'aero-tt',
    unlockLevel: 3,
    shape: 'teardrop',
    description: 'Teardrop TT lid — shaves seconds in time trials.',
    colors: { frame: '#1e3a5f', wheel: '#0f2746', kit: '#0ea5e9', skin: '#d8a877', helmet: '#1e3a5f', accent: '#38bdf8' },
  },
  {
    id: 'helmet-road',
    name: 'Road Vent',
    kind: 'helmet',
    subCategory: 'road-ventilated',
    unlockLevel: 6,
    shape: 'ventilated',
    description: 'Well-vented road helmet in forest green.',
    colors: { frame: '#166534', wheel: '#052e16', kit: '#86efac', skin: '#d8a877', helmet: '#166534', accent: '#86efac' },
  },
  {
    id: 'helmet-mtb-halfshell',
    name: 'MTB Half-Shell',
    kind: 'helmet',
    subCategory: 'mtb-halfshell',
    unlockLevel: 5,
    shape: 'halfShell',
    description: 'All-mountain half-shell for trail days.',
    colors: { frame: '#15803d', wheel: '#052e16', kit: '#4ade80', skin: '#d8a877', helmet: '#15803d', accent: '#dcfce7' },
  },
  {
    id: 'helmet-climbing',
    name: 'Climber Lid',
    kind: 'helmet',
    subCategory: 'climbing',
    unlockLevel: 7,
    shape: 'ventilated',
    description: 'Huge vents keep you cool on long Alpine climbs.',
    colors: { frame: '#fbbf24', wheel: '#b45309', kit: '#fde68a', skin: '#d8a877', helmet: '#fbbf24', accent: '#fffbeb' },
  },
  {
    id: 'helmet-aero-blue',
    name: 'Aero Shield Blue',
    kind: 'helmet',
    subCategory: 'road-aero',
    unlockLevel: 8,
    shape: 'roadAero',
    description: 'Integrated visor road aero helmet in cobalt.',
    colors: { frame: '#1d4ed8', wheel: '#1e3a8a', kit: '#93c5fd', skin: '#d8a877', helmet: '#1d4ed8', accent: '#bfdbfe' },
  },
  {
    id: 'helmet-aero-red',
    name: 'Aero Shield Red',
    kind: 'helmet',
    subCategory: 'road-aero',
    unlockLevel: 8,
    shape: 'roadAero',
    description: 'Integrated visor road aero helmet in race red.',
    colors: { frame: '#dc2626', wheel: '#991b1b', kit: '#fca5a5', skin: '#d8a877', helmet: '#dc2626', accent: '#fee2e2' },
  },
  {
    id: 'helmet-tt-white',
    name: 'TT Teardrop White',
    kind: 'helmet',
    subCategory: 'aero-tt',
    unlockLevel: 9,
    shape: 'teardrop',
    description: 'Glossy white teardrop — classic TT look.',
    colors: { frame: '#f8fafc', wheel: '#e2e8f0', kit: '#f1f5f9', skin: '#d8a877', helmet: '#f8fafc', accent: '#0ea5e9' },
  },
  {
    id: 'helmet-pro',
    name: 'Pro Aero',
    kind: 'helmet',
    subCategory: 'road-aero',
    unlockLevel: 10,
    shape: 'roadAero',
    description: 'Aero road helmet — the race-day choice of professionals.',
    colors: { frame: '#1c1c1e', wheel: '#0f0f0f', kit: '#f59e0b', skin: '#d8a877', helmet: '#1c1c1e', accent: '#f59e0b' },
  },
  {
    id: 'helmet-mtb-fullface',
    name: 'Full-Face MTB',
    kind: 'helmet',
    subCategory: 'mtb-fullface',
    unlockLevel: 11,
    shape: 'fullFace',
    description: 'Chin-bar full-face — essential for aggressive trail riding.',
    colors: { frame: '#1c1c1e', wheel: '#0f0f0f', kit: '#27272a', skin: '#d8a877', helmet: '#1c1c1e', accent: '#ef4444' },
  },
  {
    id: 'helmet-climbing-red',
    name: 'Red Climber Lid',
    kind: 'helmet',
    subCategory: 'climbing',
    unlockLevel: 12,
    shape: 'ventilated',
    description: 'Aggressive vent pattern for mountain warriors.',
    colors: { frame: '#ef4444', wheel: '#7f1d1d', kit: '#fca5a5', skin: '#d8a877', helmet: '#ef4444', accent: '#fee2e2' },
  },
  {
    id: 'helmet-mtb-halfshell-orange',
    name: 'Trail Half-Shell Orange',
    kind: 'helmet',
    subCategory: 'mtb-halfshell',
    unlockLevel: 13,
    shape: 'halfShell',
    description: 'High-vis orange half-shell — impossible to miss on the trail.',
    colors: { frame: '#ea580c', wheel: '#431407', kit: '#fb923c', skin: '#d8a877', helmet: '#ea580c', accent: '#ffedd5' },
  },
  {
    id: 'helmet-aero-white',
    name: 'Aero Shield White',
    kind: 'helmet',
    subCategory: 'road-aero',
    unlockLevel: 14,
    shape: 'roadAero',
    description: 'Clean white aero lid — pro peloton staple.',
    colors: { frame: '#f8fafc', wheel: '#e2e8f0', kit: '#f1f5f9', skin: '#d8a877', helmet: '#f8fafc', accent: '#0ea5e9' },
  },
  {
    id: 'helmet-vintage-leather',
    name: 'Vintage Leather',
    kind: 'helmet',
    subCategory: 'vintage',
    unlockLevel: 15,
    shape: 'vintageLeather',
    description: 'Hand-stitched leather hairnet — rides like it is 1953.',
    colors: { frame: '#78350f', wheel: '#3b1f0c', kit: '#d97706', skin: '#d8a877', helmet: '#78350f', accent: '#fef3c7' },
  },
  {
    id: 'helmet-tt-black',
    name: 'TT Teardrop Black',
    kind: 'helmet',
    subCategory: 'aero-tt',
    unlockLevel: 16,
    shape: 'teardrop',
    description: 'Jet-black teardrop TT lid with UV reflective strips.',
    colors: { frame: '#1c1c1e', wheel: '#0a0a0a', kit: '#27272a', skin: '#d8a877', helmet: '#1c1c1e', accent: '#a1a1aa' },
  },
  {
    id: 'helmet-mtb-fullface-blue',
    name: 'Full-Face Cobalt',
    kind: 'helmet',
    subCategory: 'mtb-fullface',
    unlockLevel: 18,
    shape: 'fullFace',
    description: 'Cobalt blue full-face with matching visor.',
    colors: { frame: '#1d4ed8', wheel: '#1e3a8a', kit: '#60a5fa', skin: '#d8a877', helmet: '#1d4ed8', accent: '#bfdbfe' },
  },
  {
    id: 'helmet-vintage-wool',
    name: 'Wool Cap (Under-Helmet)',
    kind: 'helmet',
    subCategory: 'vintage',
    unlockLevel: 20,
    shape: 'vintageLeather',
    description: 'Classic merino wool cap — nod to the golden age of cycling.',
    colors: { frame: '#9d174d', wheel: '#500724', kit: '#fecdd3', skin: '#d8a877', helmet: '#9d174d', accent: '#fdf2f8' },
  },
  {
    id: 'helmet-halfshell-dark',
    name: 'Dark MTB Half-Shell',
    kind: 'helmet',
    subCategory: 'mtb-halfshell',
    unlockLevel: 24,
    shape: 'halfShell',
    description: 'Matte black half-shell with subtle carbon weave.',
    colors: { frame: '#1c1c1e', wheel: '#0a0a0a', kit: '#27272a', skin: '#d8a877', helmet: '#1c1c1e', accent: '#a1a1aa' },
  },
  {
    id: 'helmet-tt-purple',
    name: 'TT Teardrop Purple',
    kind: 'helmet',
    subCategory: 'aero-tt',
    unlockLevel: 28,
    shape: 'teardrop',
    description: 'Deep violet TT teardrop — bold and aerodynamic.',
    colors: { frame: '#7c3aed', wheel: '#4c1d95', kit: '#a78bfa', skin: '#d8a877', helmet: '#7c3aed', accent: '#ede9fe' },
  },
  {
    id: 'helmet-aero-team-yellow',
    name: 'Yellow & Black Aero',
    kind: 'helmet',
    subCategory: 'road-aero',
    unlockLevel: 32,
    shape: 'roadAero',
    description: 'Yellow & black team aero — inspired by Visma style.',
    colors: { frame: '#eab308', wheel: '#1c1c1e', kit: '#fde68a', skin: '#d8a877', helmet: '#eab308', accent: '#1c1c1e' },
  },
  {
    id: 'helmet-aero-team-red',
    name: 'Red Team Aero',
    kind: 'helmet',
    subCategory: 'road-aero',
    unlockLevel: 34,
    shape: 'roadAero',
    description: 'Deep red & white aero — inspired by Trek racing style.',
    colors: { frame: '#dc2626', wheel: '#1c1c1e', kit: '#fca5a5', skin: '#d8a877', helmet: '#dc2626', accent: '#f8fafc' },
  },
  {
    id: 'helmet-aero-team-green',
    name: 'Green Team Aero',
    kind: 'helmet',
    subCategory: 'road-aero',
    unlockLevel: 36,
    shape: 'roadAero',
    description: 'Forest green & black aero — inspired by Bora style.',
    colors: { frame: '#166534', wheel: '#052e16', kit: '#86efac', skin: '#d8a877', helmet: '#166534', accent: '#1c1c1e' },
  },
  {
    id: 'helmet-aero-rainbow',
    name: 'World Champion Aero',
    kind: 'helmet',
    subCategory: 'road-aero',
    unlockLevel: 35,
    shape: 'roadAero',
    description: 'Rainbow-striped aero helmet — only champions wear this.',
    colors: { frame: '#f8fafc', wheel: '#1c1c1e', kit: '#e2e8f0', skin: '#d8a877', helmet: '#f8fafc', accent: '#dc2626' },
    accentColors: { primary: '#dc2626', secondary: '#f59e0b', tertiary: '#22c55e' },
  },
  {
    id: 'helmet-climbing-lightweight',
    name: 'Ultra-Light Climber',
    kind: 'helmet',
    subCategory: 'climbing',
    unlockLevel: 42,
    shape: 'ventilated',
    description: 'Sub-150g shell — every gram matters above 2000m.',
    colors: { frame: '#f0fdf4', wheel: '#dcfce7', kit: '#86efac', skin: '#d8a877', helmet: '#f0fdf4', accent: '#22c55e' },
  },
  {
    id: 'helmet-tt-gold',
    name: 'Gold TT Teardrop',
    kind: 'helmet',
    subCategory: 'aero-tt',
    unlockLevel: 40,
    shape: 'teardrop',
    description: 'Gilded teardrop — awarded only to the fastest.',
    colors: { frame: '#78350f', wheel: '#451a03', kit: '#f59e0b', skin: '#d8a877', helmet: '#78350f', accent: '#fef3c7' },
    accentColors: { primary: '#f59e0b', secondary: '#fef3c7' },
  },
  {
    id: 'helmet-mtb-fullface-pro',
    name: 'Full-Face Carbon Pro',
    kind: 'helmet',
    subCategory: 'mtb-fullface',
    unlockLevel: 38,
    shape: 'fullFace',
    description: 'Carbon-shell full-face for EWS-level downhill racing.',
    colors: { frame: '#0f172a', wheel: '#020617', kit: '#1e293b', skin: '#d8a877', helmet: '#0f172a', accent: '#f59e0b' },
  },
  {
    id: 'helmet-road-cobalt',
    name: 'Cobalt Road Lid',
    kind: 'helmet',
    subCategory: 'road-ventilated',
    unlockLevel: 10,
    shape: 'ventilated',
    description: 'Cobalt blue vented road helmet — bright on any climb.',
    colors: { frame: '#1d4ed8', wheel: '#1e3a8a', kit: '#93c5fd', skin: '#d8a877', helmet: '#1d4ed8', accent: '#bfdbfe' },
  },
  {
    id: 'helmet-road-white',
    name: 'White Road Lid',
    kind: 'helmet',
    subCategory: 'road-ventilated',
    unlockLevel: 4,
    shape: 'ventilated',
    description: 'Classic white ventilated road helmet.',
    colors: { frame: '#f8fafc', wheel: '#e2e8f0', kit: '#f1f5f9', skin: '#d8a877', helmet: '#f8fafc', accent: '#94a3b8' },
  },
  {
    id: 'helmet-halfshell-red',
    name: 'Red MTB Half-Shell',
    kind: 'helmet',
    subCategory: 'mtb-halfshell',
    unlockLevel: 16,
    shape: 'halfShell',
    description: 'Bold red half-shell for trail riders who mean business.',
    colors: { frame: '#dc2626', wheel: '#7f1d1d', kit: '#fca5a5', skin: '#d8a877', helmet: '#dc2626', accent: '#fee2e2' },
  },
  {
    id: 'helmet-aero-ocean',
    name: 'Ocean Aero Lid',
    kind: 'helmet',
    subCategory: 'road-aero',
    unlockLevel: 22,
    shape: 'roadAero',
    description: 'Deep teal aero helmet — cool and fast.',
    colors: { frame: '#0f766e', wheel: '#042f2e', kit: '#2dd4bf', skin: '#d8a877', helmet: '#0f766e', accent: '#ccfbf1' },
  },

  // ==========================================================================
  // KITS / JERSEYS — 20+ items
  // ==========================================================================

  {
    id: 'starter-kit',
    name: 'Starter Kit',
    kind: 'kit',
    subCategory: 'casual',
    unlockLevel: 1,
    description: 'A simple cyan kit to get you rolling.',
    colors: { frame: '#e2e8f0', wheel: '#0b1220', kit: '#22d3ee', skin: '#d8a877', helmet: '#0ea5e9', accent: '#f59e0b' },
  },
  {
    id: 'sunset-racer',
    name: 'Sunset Racer',
    kind: 'kit',
    subCategory: 'modern',
    unlockLevel: 3,
    description: 'Fiery orange gradient jersey — race-day energy.',
    colors: { frame: '#1e293b', wheel: '#0b1220', kit: '#f97316', skin: '#d8a877', helmet: '#fbbf24', accent: '#ef4444' },
  },
  {
    id: 'royal-sprint',
    name: 'Royal Sprint',
    kind: 'kit',
    subCategory: 'modern',
    unlockLevel: 6,
    description: 'Royal indigo with pink accents — made for sprint finishes.',
    colors: { frame: '#e2e8f0', wheel: '#0b1220', kit: '#6366f1', skin: '#d8a877', helmet: '#4f46e5', accent: '#f472b6' },
  },
  {
    id: 'volcano-kit',
    name: 'Volcano',
    kind: 'kit',
    subCategory: 'modern',
    unlockLevel: 8,
    description: 'Erupting red kit with volcanic orange accents.',
    colors: { frame: '#292524', wheel: '#1c1917', kit: '#dc2626', skin: '#d8a877', helmet: '#991b1b', accent: '#f97316' },
  },
  {
    id: 'kit-fluoro-yellow',
    name: 'Fluoro Yellow Kit',
    kind: 'kit',
    subCategory: 'modern',
    unlockLevel: 9,
    description: 'High-vis fluoro yellow — see and be seen.',
    colors: { frame: '#ca8a04', wheel: '#1c1c1e', kit: '#fde047', skin: '#d8a877', helmet: '#eab308', accent: '#1c1c1e' },
  },
  {
    id: 'cobalt-aero-kit',
    name: 'Cobalt Race Kit',
    kind: 'kit',
    subCategory: 'modern',
    unlockLevel: 10,
    description: 'Cobalt blue race kit — clean lines, fast looks.',
    colors: { frame: '#1e3a5f', wheel: '#0f2746', kit: '#3b82f6', skin: '#d8a877', helmet: '#1d4ed8', accent: '#93c5fd' },
  },
  {
    id: 'kit-fluoro-pink',
    name: 'Fluoro Pink Kit',
    kind: 'kit',
    subCategory: 'modern',
    unlockLevel: 11,
    description: 'Neon pink kit — you will not be missed in the bunch.',
    colors: { frame: '#db2777', wheel: '#831843', kit: '#f472b6', skin: '#d8a877', helmet: '#be185d', accent: '#fdf2f8' },
  },
  {
    id: 'neon-sprint',
    name: 'Neon Sprint',
    kind: 'kit',
    subCategory: 'modern',
    unlockLevel: 12,
    description: 'Neon green on black — high-visibility sprinter style.',
    colors: { frame: '#0d0d0d', wheel: '#050505', kit: '#a3e635', skin: '#d8a877', helmet: '#4ade80', accent: '#facc15' },
  },
  {
    id: 'kit-modern-dark',
    name: 'Dark Stealth Kit',
    kind: 'kit',
    subCategory: 'modern',
    unlockLevel: 13,
    description: 'All-black race kit — disappear into the pack.',
    colors: { frame: '#0f172a', wheel: '#050a15', kit: '#1e293b', skin: '#d8a877', helmet: '#334155', accent: '#64748b' },
  },
  {
    id: 'deep-space',
    name: 'Deep Space',
    kind: 'kit',
    subCategory: 'modern',
    unlockLevel: 16,
    description: 'Purple on black — the void between stars.',
    colors: { frame: '#0a0a1a', wheel: '#04040d', kit: '#7c3aed', skin: '#d8a877', helmet: '#5b21b6', accent: '#818cf8' },
  },
  {
    id: 'kit-classic-wool',
    name: 'Classic Wool Jersey',
    kind: 'kit',
    subCategory: 'vintage',
    unlockLevel: 17,
    description: 'Retro merino wool jersey in classic cream & navy.',
    colors: { frame: '#1e3a8a', wheel: '#1e3a5f', kit: '#f5f0e8', skin: '#d8a877', helmet: '#1e3a8a', accent: '#1e3a8a' },
    accentColors: { primary: '#f5f0e8', secondary: '#1e3a8a' },
  },
  {
    id: 'legend-gold',
    name: 'Legend',
    kind: 'kit',
    subCategory: 'premium',
    unlockLevel: 20,
    description: 'Gold and bronze — for those who ride into legend.',
    colors: { frame: '#78350f', wheel: '#451a03', kit: '#f59e0b', skin: '#d8a877', helmet: '#d97706', accent: '#fef3c7' },
  },
  {
    id: 'kit-sprinter-green',
    name: 'Sprinter Green',
    kind: 'kit',
    subCategory: 'sprinter',
    unlockLevel: 26,
    description: 'Points jersey green — for the bunch-sprint specialists.',
    colors: { frame: '#16a34a', wheel: '#052e16', kit: '#22c55e', skin: '#d8a877', helmet: '#15803d', accent: '#f0fdf4' },
    accentColors: { primary: '#22c55e', secondary: '#052e16' },
  },
  {
    id: 'kit-leader-yellow',
    name: 'Leader Yellow',
    kind: 'kit',
    subCategory: 'leader',
    unlockLevel: 28,
    description: 'The maillot jaune — for the overall leader.',
    colors: { frame: '#eab308', wheel: '#1c1c1e', kit: '#fde047', skin: '#d8a877', helmet: '#ca8a04', accent: '#fffbeb' },
    accentColors: { primary: '#fde047', secondary: '#1c1c1e' },
  },
  {
    id: 'kit-kom-polka',
    name: 'KOM Polka Dot',
    kind: 'kit',
    subCategory: 'kom',
    unlockLevel: 30,
    description: 'Red & white polka-dot — mountain king style.',
    colors: { frame: '#dc2626', wheel: '#7f1d1d', kit: '#dc2626', skin: '#d8a877', helmet: '#991b1b', accent: '#f8fafc' },
    accentColors: { primary: '#dc2626', secondary: '#f8fafc' },
  },
  {
    id: 'kit-team-yellow-black',
    name: 'Yellow & Black Team',
    kind: 'kit',
    subCategory: 'team-replica',
    unlockLevel: 32,
    description: 'Yellow & black — inspired by Visma-Lease a Bike style.',
    colors: { frame: '#eab308', wheel: '#1c1c1e', kit: '#fde047', skin: '#d8a877', helmet: '#ca8a04', accent: '#1c1c1e' },
    accentColors: { primary: '#fde047', secondary: '#1c1c1e' },
  },
  {
    id: 'kit-team-red-white',
    name: 'Red & White Team',
    kind: 'kit',
    subCategory: 'team-replica',
    unlockLevel: 33,
    description: 'Red, white & black — inspired by Trek-Segafredo style.',
    colors: { frame: '#dc2626', wheel: '#1c1c1e', kit: '#ef4444', skin: '#d8a877', helmet: '#991b1b', accent: '#f8fafc' },
    accentColors: { primary: '#ef4444', secondary: '#f8fafc', tertiary: '#1c1c1e' },
  },
  {
    id: 'kit-team-green-black',
    name: 'Green & Black Team',
    kind: 'kit',
    subCategory: 'team-replica',
    unlockLevel: 34,
    description: 'Forest green & black — inspired by Bora-Hansgrohe style.',
    colors: { frame: '#166534', wheel: '#052e16', kit: '#22c55e', skin: '#d8a877', helmet: '#15803d', accent: '#1c1c1e' },
    accentColors: { primary: '#22c55e', secondary: '#1c1c1e' },
  },
  {
    id: 'kit-team-blue-white',
    name: 'Blue & White Team',
    kind: 'kit',
    subCategory: 'team-replica',
    unlockLevel: 35,
    description: 'Sky blue & white — inspired by Soudal Quick-Step style.',
    colors: { frame: '#1d4ed8', wheel: '#f8fafc', kit: '#3b82f6', skin: '#d8a877', helmet: '#1d4ed8', accent: '#f8fafc' },
    accentColors: { primary: '#3b82f6', secondary: '#f8fafc' },
  },
  {
    id: 'kit-team-orange-black',
    name: 'Orange & Black Team',
    kind: 'kit',
    subCategory: 'team-replica',
    unlockLevel: 36,
    description: 'UAE orange & black — inspired by UAE Team Emirates style.',
    colors: { frame: '#ea580c', wheel: '#1c1c1e', kit: '#f97316', skin: '#d8a877', helmet: '#c2410c', accent: '#1c1c1e' },
    accentColors: { primary: '#f97316', secondary: '#1c1c1e' },
  },
  {
    id: 'kit-team-pink-blue',
    name: 'Pink & Blue Team',
    kind: 'kit',
    subCategory: 'team-replica',
    unlockLevel: 37,
    description: 'Cannonball pink & blue — inspired by EF Education style.',
    colors: { frame: '#ec4899', wheel: '#1d4ed8', kit: '#f472b6', skin: '#d8a877', helmet: '#db2777', accent: '#bfdbfe' },
    accentColors: { primary: '#f472b6', secondary: '#60a5fa' },
  },
  {
    id: 'kit-world-champion',
    name: 'World Champion Rainbow',
    kind: 'kit',
    subCategory: 'world-champion',
    unlockLevel: 45,
    description: 'The rainbow jersey — only the best in the world earn this.',
    colors: { frame: '#f8fafc', wheel: '#1c1c1e', kit: '#f8fafc', skin: '#d8a877', helmet: '#f8fafc', accent: '#dc2626' },
    accentColors: { primary: '#dc2626', secondary: '#f59e0b', tertiary: '#22c55e' },
  },

  // ==========================================================================
  // GLASSES — 10+ items
  // ==========================================================================

  {
    id: 'glasses-starter',
    name: 'Basic Sunglasses',
    kind: 'glasses',
    subCategory: 'classic',
    unlockLevel: 1,
    shape: 'classic',
    description: 'Simple black-frame sunglasses.',
    colors: { frame: '#1c1c1e', wheel: '#374151', kit: '#6b7280', skin: '#d8a877', helmet: '#1c1c1e', accent: '#6b7280' },
  },
  {
    id: 'glasses-classic-round',
    name: 'Classic Round',
    kind: 'glasses',
    subCategory: 'classic',
    unlockLevel: 4,
    shape: 'round',
    description: 'Round lens frames — retro cycling aesthetic.',
    colors: { frame: '#78350f', wheel: '#92400e', kit: '#d97706', skin: '#d8a877', helmet: '#78350f', accent: '#fef3c7' },
  },
  {
    id: 'glasses-clear',
    name: 'Clear Shield',
    kind: 'glasses',
    subCategory: 'clear',
    unlockLevel: 5,
    shape: 'shield',
    description: 'Clear lens — for overcast days and tunnel protection.',
    colors: { frame: '#e2e8f0', wheel: '#cbd5e1', kit: '#f1f5f9', skin: '#d8a877', helmet: '#94a3b8', accent: '#f8fafc' },
  },
  {
    id: 'glasses-aero-shield',
    name: 'Aero Shield',
    kind: 'glasses',
    subCategory: 'aero-shield',
    unlockLevel: 7,
    shape: 'shield',
    description: 'Single-lens aero shield — max coverage, max aero.',
    colors: { frame: '#0f172a', wheel: '#1e293b', kit: '#334155', skin: '#d8a877', helmet: '#0f172a', accent: '#38bdf8' },
  },
  {
    id: 'glasses-wraparound',
    name: 'Wraparound Race',
    kind: 'glasses',
    subCategory: 'wraparound',
    unlockLevel: 10,
    shape: 'wraparound',
    description: 'Wide wraparound lenses — zero wind gap.',
    colors: { frame: '#dc2626', wheel: '#7f1d1d', kit: '#ef4444', skin: '#d8a877', helmet: '#991b1b', accent: '#fee2e2' },
  },
  {
    id: 'glasses-oversized',
    name: 'Oversized Aero',
    kind: 'glasses',
    subCategory: 'oversized',
    unlockLevel: 12,
    shape: 'oversized',
    description: 'Maximum coverage oversized lens — also totally on-trend.',
    colors: { frame: '#1c1c1e', wheel: '#0a0a0a', kit: '#27272a', skin: '#d8a877', helmet: '#1c1c1e', accent: '#d1d5db' },
  },
  {
    id: 'glasses-photochromic',
    name: 'Photochromic Pro',
    kind: 'glasses',
    subCategory: 'photochromic',
    unlockLevel: 15,
    shape: 'wraparound',
    description: 'Auto-tinting lenses — adapts from cloud to sun in seconds.',
    colors: { frame: '#475569', wheel: '#334155', kit: '#94a3b8', skin: '#d8a877', helmet: '#64748b', accent: '#f1f5f9' },
  },
  {
    id: 'glasses-mirrored-blue',
    name: 'Blue Mirror Shield',
    kind: 'glasses',
    subCategory: 'mirrored',
    unlockLevel: 20,
    shape: 'shield',
    description: 'Icy blue mirror lens — polarised for the brightest days.',
    colors: { frame: '#0f172a', wheel: '#1e293b', kit: '#1e3a8a', skin: '#d8a877', helmet: '#1d4ed8', accent: '#bfdbfe' },
  },
  {
    id: 'glasses-mirrored-gold',
    name: 'Gold Mirror Shield',
    kind: 'glasses',
    subCategory: 'mirrored',
    unlockLevel: 22,
    shape: 'shield',
    description: 'Gold-mirror single lens — the showstopper look.',
    colors: { frame: '#78350f', wheel: '#451a03', kit: '#f59e0b', skin: '#d8a877', helmet: '#d97706', accent: '#fef3c7' },
  },
  {
    id: 'glasses-tt-visor',
    name: 'TT Aero Visor',
    kind: 'glasses',
    subCategory: 'aero-shield',
    unlockLevel: 30,
    shape: 'shield',
    description: 'Integrated TT visor — seamless with teardrop helmets.',
    colors: { frame: '#7c3aed', wheel: '#4c1d95', kit: '#8b5cf6', skin: '#d8a877', helmet: '#6d28d9', accent: '#ede9fe' },
  },
  {
    id: 'glasses-rainbow',
    name: 'Rainbow Mirror Shield',
    kind: 'glasses',
    subCategory: 'mirrored',
    unlockLevel: 48,
    shape: 'shield',
    description: 'Dichroic rainbow mirror coating — championship bling.',
    colors: { frame: '#f8fafc', wheel: '#e2e8f0', kit: '#f1f5f9', skin: '#d8a877', helmet: '#f8fafc', accent: '#dc2626' },
    accentColors: { primary: '#dc2626', secondary: '#f59e0b', tertiary: '#22c55e' },
  },

  // ==========================================================================
  // SHOES — 6+ items
  // ==========================================================================

  {
    id: 'shoes-road-carbon',
    name: 'Road Carbon',
    kind: 'shoes',
    subCategory: 'road',
    unlockLevel: 4,
    shape: 'roadCarbon',
    description: 'Stiff carbon sole road shoes — maximum power transfer.',
    colors: { frame: '#1c1c1e', wheel: '#0f0f0f', kit: '#374151', skin: '#d8a877', helmet: '#1c1c1e', accent: '#dc2626' },
  },
  {
    id: 'shoes-gravel',
    name: 'Gravel Adventure',
    kind: 'shoes',
    subCategory: 'gravel',
    unlockLevel: 7,
    shape: 'gravelShoe',
    description: 'Walkable gravel shoes — cleat recessed for hike-a-bike.',
    colors: { frame: '#92400e', wheel: '#3b1f0c', kit: '#d97706', skin: '#d8a877', helmet: '#78350f', accent: '#fef3c7' },
  },
  {
    id: 'shoes-mtb-clip',
    name: 'MTB Clipless',
    kind: 'shoes',
    subCategory: 'mtb',
    unlockLevel: 9,
    shape: 'mtbShoe',
    description: 'Two-bolt MTB clipless — grippy sole for off-bike sections.',
    colors: { frame: '#15803d', wheel: '#052e16', kit: '#4ade80', skin: '#d8a877', helmet: '#166534', accent: '#dcfce7' },
  },
  {
    id: 'shoes-fluoro',
    name: 'Fluoro Flyer',
    kind: 'shoes',
    subCategory: 'road',
    unlockLevel: 14,
    shape: 'roadCarbon',
    description: 'High-vis fluoro yellow — your feet will be noticed.',
    colors: { frame: '#eab308', wheel: '#ca8a04', kit: '#fde047', skin: '#d8a877', helmet: '#a16207', accent: '#fffbeb' },
  },
  {
    id: 'shoes-vintage-leather',
    name: 'Vintage Leather',
    kind: 'shoes',
    subCategory: 'vintage',
    unlockLevel: 18,
    shape: 'vintage',
    description: 'Hand-lasted leather cycling shoes — Eddy Merckx era chic.',
    colors: { frame: '#78350f', wheel: '#3b1f0c', kit: '#a16207', skin: '#d8a877', helmet: '#92400e', accent: '#fef9c3' },
  },
  {
    id: 'shoes-road-white',
    name: 'Pro Road White',
    kind: 'shoes',
    subCategory: 'road',
    unlockLevel: 25,
    shape: 'roadCarbon',
    description: 'Clean pro-white carbon sole shoes — peloton staple.',
    colors: { frame: '#f8fafc', wheel: '#e2e8f0', kit: '#f1f5f9', skin: '#d8a877', helmet: '#cbd5e1', accent: '#0ea5e9' },
  },

  // ==========================================================================
  // BOTTLES — 6+ items
  // ==========================================================================

  {
    id: 'bottle-white',
    name: 'White Classic',
    kind: 'bottle',
    subCategory: 'standard',
    unlockLevel: 1,
    description: 'Standard 600ml road bottle — clean white.',
    colors: { frame: '#f8fafc', wheel: '#e2e8f0', kit: '#f1f5f9', skin: '#d8a877', helmet: '#cbd5e1', accent: '#0ea5e9' },
  },
  {
    id: 'bottle-neon',
    name: 'Neon Hydrator',
    kind: 'bottle',
    subCategory: 'standard',
    unlockLevel: 5,
    description: 'Neon green — impossible to lose in a bottle cage.',
    colors: { frame: '#4ade80', wheel: '#052e16', kit: '#86efac', skin: '#d8a877', helmet: '#22c55e', accent: '#f0fdf4' },
  },
  {
    id: 'bottle-vintage-steel',
    name: 'Vintage Steel Bidon',
    kind: 'bottle',
    subCategory: 'vintage',
    unlockLevel: 15,
    description: 'Stainless steel bidon — proper old-school.',
    colors: { frame: '#9ca3af', wheel: '#4b5563', kit: '#d1d5db', skin: '#d8a877', helmet: '#6b7280', accent: '#f9fafb' },
  },
  {
    id: 'bottle-team-replica',
    name: 'Team Replica Bottle',
    kind: 'bottle',
    subCategory: 'team-replica',
    unlockLevel: 20,
    description: 'Orange & black team colours — inspired by UAE Team Emirates.',
    colors: { frame: '#ea580c', wheel: '#1c1c1e', kit: '#f97316', skin: '#d8a877', helmet: '#c2410c', accent: '#fed7aa' },
  },
  {
    id: 'bottle-aero-stealth',
    name: 'Aero Stealth Bottle',
    kind: 'bottle',
    subCategory: 'aero',
    unlockLevel: 28,
    shape: 'aero',
    description: 'Aero-profiled down-tube bottle — shaped to match your frame.',
    colors: { frame: '#1c1c1e', wheel: '#0a0a0a', kit: '#27272a', skin: '#d8a877', helmet: '#1c1c1e', accent: '#a1a1aa' },
  },
  {
    id: 'bottle-rainbow',
    name: 'Rainbow Champion Bottle',
    kind: 'bottle',
    subCategory: 'premium',
    unlockLevel: 45,
    description: 'Rainbow-striped premium bottle — for the elite.',
    colors: { frame: '#f8fafc', wheel: '#1c1c1e', kit: '#e2e8f0', skin: '#d8a877', helmet: '#f8fafc', accent: '#dc2626' },
    accentColors: { primary: '#dc2626', secondary: '#f59e0b', tertiary: '#22c55e' },
  },
];

// ---------------------------------------------------------------------------
// HELMETS — legacy export kept for backward compat with Garage.tsx
// Derived from GEAR_CATALOG helmet entries so there is a single source of truth.
// ---------------------------------------------------------------------------

/** @deprecated Use GEAR_CATALOG filtered by kind='helmet' instead. */
export const HELMETS: HelmetItem[] = GEAR_CATALOG
  .filter((g) => g.kind === 'helmet')
  .map((g) => ({
    id: g.id,
    name: g.name,
    defaultColor: g.colors.helmet,
    accentColor: g.colors.accent,
    unlockLevel: g.unlockLevel,
  }));

// ---------------------------------------------------------------------------
// Helpers (legacy — see also src/lib/gear/gearByCategory.ts)
// ---------------------------------------------------------------------------

/** All gear items unlocked at or below `level`. */
export function unlockedGear(level: number): GearItem[] {
  return GEAR_CATALOG.filter((g) => g.unlockLevel <= level);
}

/** Whether a specific gear item is unlocked for the given level. */
export function isUnlocked(gearId: string, level: number): boolean {
  const item = GEAR_CATALOG.find((g) => g.id === gearId);
  return item ? item.unlockLevel <= level : false;
}
