/**
 * raceStore.ts — Stub for Wave 21.A
 *
 * Zustand store that persists loaded race manifests and locally-recorded
 * results in localStorage.  Wave 21.A owns the canonical implementation;
 * this stub satisfies the documented contract so the UI compiles.
 *
 * DO NOT edit this file — it will be replaced wholesale by Wave 21.A.
 */

import { create } from 'zustand';
import { persist, createJSONStorage } from 'zustand/middleware';
import type { RaceManifest, RaceResult } from '@/lib/race/raceProtocol';

interface RaceStoreState {
  /** All manifests loaded into the app (via import or create). */
  loadedManifests: RaceManifest[];
  /**
   * Local + peer-imported results keyed by raceId.
   * Each array is sorted ascending by finishTimeMs.
   */
  localResults: Record<string, RaceResult[]>;

  // ── Actions ────────────────────────────────────────────────────────────────
  /** Add or replace a manifest (idempotent by id). */
  loadManifest: (manifest: RaceManifest) => void;
  /** Remove a manifest and its associated local results. */
  removeManifest: (raceId: string) => void;
  /** Record a peer-imported result for a race. */
  importPeerResult: (result: RaceResult) => void;
}

export const useRaceStore = create<RaceStoreState>()(
  persist(
    (set, _get) => ({
      loadedManifests: [],
      localResults: {},

      loadManifest(manifest) {
        set((s) => ({
          loadedManifests: [
            ...s.loadedManifests.filter((m) => m.id !== manifest.id),
            manifest,
          ],
        }));
      },

      removeManifest(raceId) {
        set((s) => {
          const results = { ...s.localResults };
          delete results[raceId];
          return {
            loadedManifests: s.loadedManifests.filter((m) => m.id !== raceId),
            localResults: results,
          };
        });
      },

      importPeerResult(result) {
        set((s) => {
          const existing = s.localResults[result.raceId] ?? [];
          // Deduplicate by rideHash
          const deduped = existing.filter((r) => r.rideHash !== result.rideHash);
          const updated = [...deduped, result].sort((a, b) => a.finishTimeMs - b.finishTimeMs);
          return {
            localResults: {
              ...s.localResults,
              [result.raceId]: updated,
            },
          };
        });
      },
    }),
    {
      name: 'globeride.races',
      storage: createJSONStorage(() => localStorage),
    },
  ),
);
