/**
 * raceProtocol.ts — Stub for Wave 21.A
 *
 * Defines the RaceManifest and RaceResult shapes plus the encode/decode/parse
 * helpers used by RaceLobby and raceStore.  Wave 21.A owns the canonical
 * implementation; this stub satisfies the documented contract so that the UI
 * and store compile while that agent's work is pending.
 *
 * DO NOT edit this file — it will be replaced wholesale by Wave 21.A.
 */

import type { Route } from '@/types';

// ─── Core types ──────────────────────────────────────────────────────────────

export interface RaceManifest {
  id: string;
  schemaVersion: 1;
  name: string;
  description?: string;
  routeRef: {
    kind: 'iconic' | 'wts' | 'inline';
    /** id matching an ICONIC_ROUTES entry (.route.id) */
    routeId?: string;
    /** id matching a WORLD_TOUR_STAGES entry (.route.id) */
    stageId?: string;
    /** full inline Route payload for custom routes */
    route?: Route;
  };
  utcWindow: {
    /** Race open timestamp, Unix ms */
    startMs: number;
    /** Race close timestamp, Unix ms */
    endMs: number;
  };
  rules: {
    laps?: number;
    requireWorkout?: boolean;
    /** Minimum average speed to count as a valid finish, km/h */
    minSpeedKmh?: number;
    /** Maximum average W/kg — cat limit */
    maxAvgPowerWPerKg?: number;
  };
  organiser?: { name: string };
  /** Unix ms the manifest was created */
  createdAt: number;
}

export interface RaceResult {
  raceId: string;
  rider: {
    name: string;
    ftpW?: number;
    weightKg?: number;
  };
  /** Elapsed finish time, ms */
  finishTimeMs: number;
  avgPowerW?: number;
  totalAscentM: number;
  /** Unix ms when the result was recorded locally */
  recordedAt: number;
  /** SHA-256 hex of the raw telemetry (anti-cheat) */
  rideHash: string;
  /** Ed25519 signature (placeholder in stub) */
  signature: string;
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

/** Create a new RaceManifest from partial options (fills id + createdAt). */
export function createManifest(
  opts: Omit<RaceManifest, 'id' | 'schemaVersion' | 'createdAt'>,
): RaceManifest {
  return {
    ...opts,
    id: `race-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
    schemaVersion: 1,
    createdAt: Date.now(),
  };
}

/**
 * Encode a RaceManifest as a shareable URL query param.
 * Returns a full URL string: `<origin>?race=<base64>`.
 */
export function encodeManifestUrl(manifest: RaceManifest): string {
  const payload = btoa(unescape(encodeURIComponent(JSON.stringify(manifest))));
  return `${window.location.origin}${window.location.pathname}?race=${payload}`;
}

/**
 * Decode a race manifest from a URL string.
 * Returns null if the URL has no `race=` param or if decoding fails.
 */
export function decodeManifestUrl(url: string): RaceManifest | null {
  try {
    const u = new URL(url, window.location.origin);
    const raw = u.searchParams.get('race');
    if (!raw) return null;
    const json = decodeURIComponent(escape(atob(raw)));
    const parsed = JSON.parse(json) as RaceManifest;
    if (!parsed.id || parsed.schemaVersion !== 1) return null;
    return parsed;
  } catch {
    return null;
  }
}

/**
 * Parse a `.race.json` File into a RaceManifest.
 * Rejects with an error message if the file is malformed.
 */
export async function parseManifestFile(file: File): Promise<RaceManifest> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = (e) => {
      try {
        const text = e.target?.result as string;
        const parsed = JSON.parse(text) as RaceManifest;
        if (!parsed.id || parsed.schemaVersion !== 1) {
          reject(new Error('Invalid .race.json — missing id or wrong schemaVersion'));
          return;
        }
        resolve(parsed);
      } catch {
        reject(new Error('Failed to parse .race.json — invalid JSON'));
      }
    };
    reader.onerror = () => reject(new Error('Could not read file'));
    reader.readAsText(file);
  });
}
